Repository Techeer-log/Techeer-log, pull requests merged in 2024-10, with the labels that each got.

#380 [fix] docker volume mounting
  docker-compose.ec2.yml
Labels: devops

#383 [fix] compose 파일 로그 저장 경로 수정
  docker-compose.ec2.yml
Labels: bug, devops

#385 [fix] log 적용 에러 수정
  docker-compose.ec2.yml
Labels: bug, devops

#398 [feat] 코드 스플리팅 적용 및 로그인, 회원가입 페이지 배경 이미지 webp 변환
  frontend/src/entities/ProjectTabs/ui/ProjectTabs.tsx
  frontend/src/entities/login/ui/LogIn.tsx
  frontend/src/entities/myPage/ui/scrapList.tsx
  frontend/src/entities/myPage/ui/uploadList.tsx
  frontend/src/entities/projectList/ui/projectList.tsx
  frontend/src/entities/signup/ui/SignUp.tsx
  frontend/src/feature/ProjectWrite/DeferredComponent.tsx.tsx
  frontend/src/pages/MainPage.tsx
  frontend/src/pages/Project/ProjectPage.tsx
  frontend/src/shared/assets/image/loginImg/Background-Login.png
  frontend/src/shared/assets/image/loginImg/Background-Login.webp
  frontend/src/shared/assets/image/signupImg/signup.svg
  frontend/src/shared/assets/image/signupImg/signup.webp
  frontend/src/shared/ui/SkeletonCard.tsx
  package-lock.json
  package.json
Labels: feature, frontend
